version: '3.9'

services:
  web:
    build: .
    container_name: django-backend
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    depends_on:
      - db
      - redis
    environment:
      - DEBUG=1
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/apra_nova_db
      - VIRTUAL_HOST=backend.localhost
      - VIRTUAL_PORT=8000        # <-- Required for nginx-proxy routing
      - LETSENCRYPT_HOST=backend.localhost
      - LETSENCRYPT_EMAIL=dev@localhost
      - BASE_DOMAIN=apranova.com
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    expose:
      - "8000"
    networks:
      - proxy

  db:
    image: postgres:13
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: apra_nova_db
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - proxy

  redis:
    image: redis:alpine
    container_name: redis-cache
    restart: always
    networks:
      - proxy

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
    environment:
      - DEFAULT_HOST=backend.localhost
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs:ro
      - ./vhost.d:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
    networks:
      - proxy

networks:
  proxy:
    driver: bridge

volumes:
  db_data:
